main:
  project_name: "starter"  
  data:
    pth: '../data/census.csv'
    categorical_features: 
      - 'marital-status'
      - 'occupation'
      - 'relationship'
      - 'education'
      - 'race'
      - 'sex'
      - 'workclass'
      - 'native-country'
      - 'salary'
    label: 'salary'
  train_test_split:
      test_size: 0.2
      random_state: 1234
  modeling:
    FEATURES:
      categorical:
        - 'marital-status'
        - 'occupation'
        - 'relationship'
        - 'race'
        - 'sex'
        - 'workclass'
        - 'native-country'
        - 'education'
      numeric:
        - 'age'
        - 'fnlgt'
        - 'capital-gain'
        - 'capital-loss'
        - 'hours-per-week'
    MODEL: 
      XGBClassifier:
        objective: 'binary:logistic'
        eval_metric: 'logloss'
    param_grid:
      model__n_estimators: 
        - 50
        - 100
        - 200
      model__max_depth: 
        - 3
        - 5
        - 7
      model__learning_rate: 
        - 0.01
        - 0.1
        - 0.2
      model__subsample: 
        - 0.8
        - 1.0
      model__colsample_bytree: 
        - 0.8
        - 1.0
    slice_output:
        slice_evaluation_by_feature: True
        categorical_features: 
        - 'sex'
    output_dir: '../results'
    model_dir : '../model'

best_model_dir: "../model/best_model.pkl"
example_dir: "app/examples.yaml"

