name: Python CI
on: 
  push:  # Trigger action on push events
    branches:
      - development # Run only on pushes to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The OS to run the job on
    strategy:
      matrix:
        python-version: [3.10.16]  # You can add more versions like [3.8, 3.9, 3.10] to test against multiple versions

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to latest stable v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3  # Updated to latest stable v3
      with:
        python-version: ${{matrix.python-version }}

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  # Install dependencies if requirements.txt exists

    # Run pytest to execute tests
    - name: Run pytest
      run: |
        pytest src/tests -vv  # Run pytest with verbose output (adjust test paths if necessary)
    # Run flake8 to check code style
    - name: Run flake8
      run: |
        flake8 --max-line-length=130  # Run flake8 on the repository (adjust paths if necessary)

  