name: Python CI

on:
  push:
    branches:
      - main  # or 'master' if your default branch is 'master'
  pull_request:
    branches:
      - main  # or 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Use the latest Python 3 version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assumes your dependencies are in requirements.txt

    # Run flake8
    - name: Run flake8
      run: |
        pip install flake8
        flake8 .  # Runs flake8 on the repository (adjust paths if necessary)

    # Run pytest
    - name: Run pytest
      run: |
        pip install pytest
        pytest --maxfail=1 --disable-warnings -q  # Run pytest with options
